sudo: required
language: c
env:
    matrix:
        - OS_TYPE=fedora
        - OS_TYPE=centos:8
        - OS_TYPE=centos:7
        - OS_TYPE=ubuntu:18.04

services:
    - docker

before_install:
    - docker pull $OS_TYPE

script:
    - travis_wait 30
        docker run --privileged --rm=true --tty=true
        -v `pwd`:/libstoragemgmt-code:rw $OS_TYPE
        /bin/bash -c /libstoragemgmt-code/test/docker_travis_test.sh
