version: 2.1
jobs:
  fedora:
    docker:
      - image: fedora
    steps:
      - checkout # check out the code in the project directory
      - run: cd libstoragemgmt
      - run: ./test/docker_travis_test.sh